### ISSUE TITLE
Running build twice produces vastly different CSS output with less-openui 0.5.2

### ISSUE THREAD

**Issue by cmastrandrea** [SAP/less-openui5#24] opened 2018-05-16 17:04 UTC
OpenUI5 version: 1.54.4 (with less-openui5 0.5.2)

Browser/version (+device/version): N/A

Any other tested browsers/devices(OK/FAIL): N/A

URL (minimal example if possible):  N/A

User/password (if required and possible - do not post any confidential information here):  N/A

Steps to reproduce the problem: 
1.  Run build of an OpenUI5 library project by calling grunt build
2.  Rename the target directory target.one
3.  Run the build again
4.  Compare the target and target.one directories

What is the expected result?  Contents of the directories from the two different builds are the same.

What happens instead?  Contents can be vastly different.

Any other information? (attach screenshot if possible)
In our case, the project being built has a reasonably complex .less inheritance/import chain.  There could be up to 5 levels of inheritance to a single theme.  For example, the inheritance chain for one of our themes (from the less files with least precedence to most) is:
base > sap_belize > sas_base > sas_corporate

It seems like less files are getting loaded or processed in different orders between builds.  We don’t know if this has to do with the asynchronous file loading introduced between 0.2.0 and 0.5.2.  In our debugging, we put log messages in lib/fileUtils – before line 64, which is the fs.readFile(fileInfo.path, { line and before line 70, which is the resolve({ line and saw the following for base.less:

Debug statements when incorrect CSS generated:
Reading file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\sap_belize\base.less 
Resolving file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\sap_belize\base.less 
Reading file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\base\base.less 
Reading file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\sap_belize\base.less 
Reading file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\base\base.less 
Resolving file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\base\base.less 
Resolving file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\sap_belize\base.less 
Resolving file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\base\base.less

Debug statements when correct CSS generated:
Reading file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\sap_belize\base.less 
Resolving file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\sap_belize\base.less 
Reading file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\base\base.less 
Reading file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\base\base.less 
Reading file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\sap_belize\base.less 
Resolving file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\base\base.less 
Resolving file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\base\base.less 
Resolving file: C:\dev\master\htmlcommons-themes\openui-framework-themes\build\tmp\build\unpackedOpenuiCompileAndProvidedDependencies\resources\sap\ui\core\themes\sap_belize\base.less

When sap_belize is “resolved” last, the resulting CSS is as expected.  When base, is “resolved” last, the CSS is incorrect.  We haven’t investigated what happens in “resolve”, but it looks like the last base.less “resolved” is the one that takes precedence in the CSS output.

**Comment by matz3** [comment] 2018-05-17 08:52
Sound's strange to me. I wasn't aware of such issues before.

Do you have any example of the difference in the resulting CSS? Just a different order?
Also, sharing a (reduced) setup to reproduce would be helpful for further investigation.

**Comment by cmastrandrea** [comment] 2018-05-18 18:17
Attached are two different CSS files produced from the same source, just different builds. We don't have a good set of source files to be able to upload to easily reproduce the problem, but we do have multiple levels of inheritance for our themes as you can see in the imports.

It seems likely that switching to the asynchronous loading of imports is the cause of the problem, as we've switched back to synchronous in a local copy of the tools and the problem goes away. If you don't have code to ensure that the asynchronous imports are being processed in the order that they're defined, that could certainly be a problem.

[sap-ui-suite-themes-library.zip](https://github.com/SAP/less-openui5/files/2018162/sap-ui-suite-themes-library.zip)

**Comment by matz3** [comment] 2018-06-01 14:03
Okay I see.
Usually I would expect that less handles this correctly as we only hook into the file loading (which is also async within less itself).
I need to further investigate to reproduce this as I couldn't come up with a test that fails in such a scenario. So having a minimal example would really help.
Please also provide the options you pass to less-openui5.

**Comment by cmastrandrea** [comment] 2018-06-06 14:50
This is the json representation of the 'options' object that's passed into less-openui5:

(less-openui5/lib/index.js) Builder.build - options - { rootPaths: 
   [ 'src/main/openuilibs/sap.m/src',
     'src/main/openuilibs/sap.ui.commons/src',
     'src/main/openuilibs/sap.ui.core/src',
     'src/main/openuilibs/sap.ui.demokit/src',
     'src/main/openuilibs/sap.ui.layout/src',
     'src/main/openuilibs/sap.ui.suite/src',
     'src/main/openuilibs/sap.ui.unified/src',
     'src/main/openuilibs/sap.ui.ux3/src',
     'src/main/openuilibs/sas.hc.m/src',
     'src/main/openuilibs/sas.hc.ui.commons/src',
     'src/main/openuilibs/sas.hc.ui.commons.codeEditor/src',
     'src/main/openuilibs/sas.hc.ui.core/src',
     'src/main/openuilibs/sas.hc.ui.layout/src',
     'src/main/openuilibs/sas.hc.ui.objectmgr/src',
     'src/main/openuilibs/sas.hc.ui.services.comment/src',
     'src/main/openuilibs/sas.hc.ui.services.navigation/src',
     'src/main/openuilibs/sas.hc.ui.services.search/src',
     'src/main/openuilibs/sas.hc.ui.services.userGroup/src',
     'src/main/openuilibs/sas.hc.ui.table/src',
     'src/main/openuilibs/sas.hc.x/src',
     'C:\\dev\\master\\htmlcommons-themes\\openui-framework-themes\\build\\tmp\\build\\unpackedOpenuiCompileAndProvidedDependencies/resources' ],
  rtl: true,
  parser: { relativeUrls: false },
  compiler: { compress: false, plugins: [ [Object] ] },
  library: { name: 'sap.ui.ux3' },
  lessInputPath: '/sap/ui/ux3/themes/sas_inspire/library.source.less' }

**Comment by matz3** [comment] 2018-06-27 07:38
Thanks. Unfortunately I still couldn't reproduce such behavior...
Might be even related to Windows, as I'm on a Mac.

Can you give a hint about your concrete inheritance structure? I already tried multiple nested imports, but all of them were resolved in the expected order, even after multiple test runs and random delays on file system access.

**Comment by jbragiel** [comment] 2018-11-12 15:48
I have a simple recreation scenario that happens 100% of the time for me, at least on Windows.  The error seems to be caused by the asynchronous loading and the less rule that the same source file cannot be imported twice (by default).  The sample consists of 4 files:

[less-order-issue-example.zip](https://github.com/SAP/less-openui5/files/2572542/less-order-issue-example.zip)

test_rules.less:
```
@import "test_variablesBaseOneRemoved.less"; // (1)
@import "test_variablesOverrides.less"; // (2)
@import "test_variablesBase.less"; // (3)


input {
    color: @testColor;
}
```

=======================================================

test_variablesBaseOneRemoved.less:
`@import "test_variablesBase.less"; // (1a)`

=======================================================

test_variablesBase.less:
`@testColor: #555;`

=======================================================

test_variablesOverrides.less
`@testColor: #777;`

=======================================================

What we think should be happening:
a)	test_variablesBaseOneRemoved.less (1) is processed.  Its contents just import test_variablesBase.less.   test_variablesBase.less (1a) is processed.
b)	test_variablesOverrides.less (2) is processed.
c)	test_variablesBase.less (3) is ignored since it was already imported in (1).

Expected result:  Values from test_variablesOverrides.less have highest precedence since they were loaded last.
test_rules.css:
```
input {
    color: #777;
}
```

=======================================================

What is happening:
a)	Results from the load of test_variablesBase.less (3) come back first from loading.  These are added to the compiler’s graph for processing once everything is loaded and "test_variablesBase.less" is added to the less compiler's internal list of loaded files so it won't get loaded/added again.
b)	Results from the load of variablesOverrides.less (2) come back next. These are added to the compiler’s graph for processing once everything is loaded.
c)	Results from the load of test_variablesBase.less (1a) come back last.  Since this file has already been added, it was marked as a duplicate and the contents are not added to the compiler’s graph.
d)	All contents are loaded so the processing begins:
	i.	test_variablesBaseOneRemoved (1) has no variables to process.
	ii.	test_variablesBase (1a) was marked a duplicate so there are no variables to process.
	iii.	test_variablesOverrides (2) variables are processed.
	iv.	test_variablesBase (3) variables are processed.

Actual result:  Values from test_variablesBase.less have highest precedence.
test_rules.css:
```
input {
    color: #555;
}
```

=======================================================

To double check the example, I ran it through another less compiler, less4j.  These were the results:
```
$ java -jar less4j-1.17.2.jar test_rules.less
input {
  color: #777;
}
```

**Comment by matz3** [comment] 2018-11-13 09:21
Thanks for providing an example.

As far as I can see, our project behaves the same as the standard less implementation (with v1.6.3, which is currently used in this project).

```js
var less = require("less"); // v1.6.3
var fs = require("fs");

var parser = new(less.Parser)({
    paths: ['.'],
    filename: 'test_rules.less'
});

parser.parse(fs.readFileSync('test_rules.less', { encoding: "utf-8" }), function (e, tree) {
    console.log(tree.toCSS({ compress: true }));
});
```
Output
```
input{color:#555}
```

When compiling the same files with the latest version of less (currently 3.8.1) I get the same result:
```shell
npm install -g less
lessc test_rules.less
```
```
input {
  color: #555;
}
```

Therefore I do not see this as an issue with this project but rather with less itself or how it's designed to work.
less4j seems to be a port of the JavaScript implementation which doesn't seem to behave like the original compiler.

Originally this issue seemed to be an issue with timing, where the result is not consistent. If you can provide an example for that I will have a look into it, as this is something I would not expect to happen. Therefore closing this for now.

**Comment by matz3** [comment] 2019-11-08 10:17
We now also observe inconsistent results when running a build multiple times with the exact same input. 
At first glance it seems to happen when importing the same file from multiple places.

**Comment by matz3** [comment] 2019-11-11 14:42
The problem has been reported for less v1.6.3 and has been fixed with v1.7.0: https://github.com/less/less.js/issues/1898
We will check how to address this as upgrading less is not straightforward (see https://github.com/SAP/less-openui5/issues/25#issuecomment-390175967).

**Comment by jbragiel** [comment] 2019-11-11 16:26
A couple of years ago, we forked less-openui5 internally so that we could use less v1.7.5.  I just looked at our internal commit and didn't see anything too disruptive we had to do for the minor upgrade.  There was the expected package.json less dependency change and a bunch of expected test css results files changed.  

Between less 1.6.3 and 1.7.5, it looks like less started stripping off leading inline comments so almost all of the test results changes reflected this.  Expected test results changed like this:
```
-  transform: /* some comment */ translate(-2px, 3px);
+  transform: translate(-2px, 3px);

```

**Comment by matz3** [comment] 2019-11-12 09:59
You are right, the differences are not disruptive in general. Our main issue is that we have an internal project that also compiles UI5 themes (and also themes for other UI technologies) with less v1.6.3.
If we would upgrade to a newer version, the output would differ and as v1.7.x also introduced new features, it might break on their side.

Our current plan is to have a fork of less v1.6.3 + the relevant fix within our less-openui5 project.
This would also allow us to solve #25 and with that I'm also thinking about addressing #81 to at least allow people to use e.g. v1.7.5, if that's something that would help you getting rid of your fork @jbragiel.

**Closed** 2019-11-14 16:03 UTC
Labels: bug
